mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:3>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:4>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:5>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:6>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:7>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:8>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:9>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:10>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:11>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:12>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:13>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:14>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:15>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:16>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:17>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:18>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:19>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:20>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:21>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:22>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:23>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:24>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:25>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:26>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:27>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:28>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:29>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:30>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:31>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:32>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:33>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:34>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:35>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:36>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:37>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:38>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:39>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:40>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:41>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:42>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:43>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:44>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:45>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:46>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:47>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:48>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:49>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:50>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:51>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:52>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:53>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:54>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:55>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:56>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:57>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:58>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:59>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:60>);
mods.recipestages.Recipes.setRecipeStage("A1b",<ic2:te:61>);
mods.recipestages.Recipes.setRecipeStage("A1b",<ic2:te:62>);
mods.recipestages.Recipes.setRecipeStage("A1b",<ic2:te:63>);
mods.recipestages.Recipes.setRecipeStage("A1b",<ic2:te:64>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:65>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:66>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:67>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:68>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:69>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:70>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:71>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:72>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:73>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:74>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:75>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:76>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:77>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:78>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:79>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:80>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:81>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:82>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:83>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:84>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:85>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:86>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:87>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:88>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:89>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:90>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:91>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:92>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:93>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:94>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:95>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:96>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:97>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:98>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:99>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:100>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:101>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:102>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:103>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:104>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:105>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:106>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:107>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:108>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:109>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:110>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:111>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:112>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:113>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:114>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:115>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:116>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:117>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:118>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:119>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:120>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:121>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:122>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:123>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:124>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:125>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:126>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:127>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:128>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:129>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:130>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:131>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:132>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:133>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:te:134>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:advanced_batpack:26>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:batpack:26>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:energy_pack>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:jetpack:27>);
mods.recipestages.Recipes.setRecipeStage("A1",<ic2:jetpack_electric:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:chainsaw:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:diamond_drill:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:drill:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:electric_treetap:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:electric_wrench:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:iridium_drill:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:mining_laser:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:nano_saber:26>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:electric_hoe>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:wrench>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:wrench_new>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:crowbar>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:forge_hammer>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:hazmat_helmet>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:hazmat_chestplate>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:hazmat_leggings>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:static_boots>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:nano_helmet>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:nano_chestplate>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:nano_leggings>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:nano_boots>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:quantum_helmet>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:quantum_chestplate>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:quantum_leggings>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:quantum_boots>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:rubber_boots>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:solar_helmet>);

mods.ItemStages.addItemStage("A1", <ic2:electric_wrench:26>.withTag({}));
mods.ItemStages.addItemStage("A1", <ic2:wrench>);
mods.ItemStages.addItemStage("A1", <ic2:wrench_new>);
mods.ItemStages.addItemStage("A1", <ic2:crowbar>);

mods.orestages.OreStages.addReplacement("A1", <ic2:te:1>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:2>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:3>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:4>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:5>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:6>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:7>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:8>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:9>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:10>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:11>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:12>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:13>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:14>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:15>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:16>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:17>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:18>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:19>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:20>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:21>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:22>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:23>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:24>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:25>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:26>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:27>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:28>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:29>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:30>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:31>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:32>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:33>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:34>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:35>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:36>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:37>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:38>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:39>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:40>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:41>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:42>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:43>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:44>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:45>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:46>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:47>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:48>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:49>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:50>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:51>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:52>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:53>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:54>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:55>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:56>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:57>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:58>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:59>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:60>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1b", <ic2:te:61>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1b", <ic2:te:62>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1b", <ic2:te:63>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1b", <ic2:te:64>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:65>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:66>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:67>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:68>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:69>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:70>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:71>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:72>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:73>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:74>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:75>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:76>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:77>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:78>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:79>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:80>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:81>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:82>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:83>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:84>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:85>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:86>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:87>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:88>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:89>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:90>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:91>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:92>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:93>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:94>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:95>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:96>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:97>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:98>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:99>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:100>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:101>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:102>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:103>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:104>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:105>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:106>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:107>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:108>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:109>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:110>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:111>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:112>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:113>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:114>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:115>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:116>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:117>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:118>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:119>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:120>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:121>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:122>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:123>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:124>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:125>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:126>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:127>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:128>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:129>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:130>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:131>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:132>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:133>, <ic2:resource:12>);
mods.orestages.OreStages.addReplacement("A1", <ic2:te:134>, <ic2:resource:12>);

mods.recipestages.Recipes.setRecipeStage("A1", <ic2:crop_stick>);
mods.recipestages.Recipes.setRecipeStage("A1", <ic2:weeding_trowel>);

mods.ItemStages.addItemStage("A1", <ic2:crop_stick>);
mods.ItemStages.addItemStage("A1", <ic2:weeding_trowel>);

mods.ItemStages.addItemStage("A1", <ic2:treetap>);
mods.ItemStages.addItemStage("A1", <ic2:electric_treetap:26>.withTag({}));

recipes.addShaped(<ic2:te:45>, [
[<ic2:treetap>, <ic2:resource:12>, <ic2:treetap>],
[<ic2:treetap>, <ic2:crafting:1>, <ic2:treetap>]]);